api_keys:
  slack: "xoxb-184828202626-2380531161840-Nb9EKbCphF6MHZGwOJRrYF7U" #Demo App on Texasgang
  pagerduty:
    org: "texasgang"
    key: "u+R6URd34XuAGEzjLQwg"

groups:
  - name: test1
    schedules:
      - P07UK76
    update_message:
      message: ":fire_engine: Your firefighters are %s :fire_engine:"
      channels:
        - general
